name: Build and Deploy Snapshot
on:
  push:
    branches:
    - master
    - "3.0"
    - "2.18"
    paths-ignore:
    - "README.md"
    - "release-notes/*"
  pull_request:
    branches:
    - master
    - "3.0"
    - "2.18"
    paths-ignore:
    - "README.md"
    - "release-notes/*"
jobs:
  build:
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        java_version: ['8', '11', '17', '21']
        joda_version: ['2.9', '2.10.14', '2.12.7']
    env:
      JAVA_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java_version }}
        cache: 'maven'
        server-id: sonatype-nexus-snapshots
        server-username: CI_DEPLOY_USERNAME
        server-password: CI_DEPLOY_PASSWORD
        # See https://github.com/actions/setup-java/blob/v2/docs/advanced-usage.md#Publishing-using-Apache-Maven
        # gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        # gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase
    - name: Build
      # Note: build separately first with default joda
      run: ./mvnw -B -q -ff -ntp -DskipTests clean package
    - name: Test
      # Note: actual testing to use matrix-version of Joda
      run: ./mvnw -B -q -ff -ntp -Dversion.joda=${{ matrix.joda_version }} surefire:test
    - name: Extract project Maven version
      id: projectVersion
      run: echo "version=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.3.0:evaluate -DforceStdout -Dexpression=project.version -q)" >> $GITHUB_OUTPUT
    - name: Deploy snapshot
      if: github.event_name != 'pull_request' && matrix.java_version == '8' && matrix.joda_version == '2.10.14' && endsWith(steps.projectVersion.outputs.version, '-SNAPSHOT')
      env:
        CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
        CI_DEPLOY_PASSWORD: ${{ secrets.CI_DEPLOY_PASSWORD }}
        # MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
      run: ./mvnw -B -q -ff -DskipTests -ntp source:jar deploy
    - name: Generate code coverage
      if: github.event_name != 'pull_request' && matrix.java_version == '8' && matrix.joda_version == '2.10.14' && endsWith(steps.projectVersion.outputs.version, '-SNAPSHOT')
      run: ./mvnw -B -q -ff -ntp test
    - name: Publish code coverage
      if: github.event_name != 'pull_request' && matrix.java_version == '8' && matrix.joda_version == '2.10.14' && endsWith(steps.projectVersion.outputs.version, '-SNAPSHOT')
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
